# Generated by Django 5.1.7 on 2025-04-25 14:44 # Дата генерации может отличаться

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_managers'), # Убедитесь, что зависимость правильная
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_user_id', # Исправлено имя поля
            # Исправлен тип поля и добавлены параметры из модели
            field=models.CharField(max_length=100, blank=True, null=True, unique=True, db_index=True),
            # Удаляем предыдущее неправильное поле, если оно было добавлено по ошибке
            # Если миграция 0004 уже применялась, может потребоваться сначала удалить поле telegram_id
            # migrations.RemoveField(
            #     model_name='user',
            #     name='telegram_id',
            # ),
        ),
    ]
