# Generated by Django 5.1.7 on 2025-04-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, help_text="URL изображения или класс иконки (например, 'fas fa-beer')", max_length=255),
        ),
    ]
